server:
  port: 8120

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/newgang
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwerty1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update